<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yrl</string>
	</array>
	<key>name</key>
	<string>Yecc (Erlang)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nonterminals-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#terminals-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expect-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rootsymbol-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#endsymbol-directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rule</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#erlang-code</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>(%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.erlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.yecc</string>
		</dict>
		<key>endsymbol-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Endsymbol)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.endsymbol.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.endsymbol.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#token</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>erlang-code</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Erlang\s+code)\s*(\.)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.code.yecc</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!)</string>
			<key>name</key>
			<string>meta.section.code.yecc source.erlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.erlang</string>
				</dict>
			</array>
		</dict>
		<key>expect-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Expect)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.expect.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.expect.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#integer</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>integer</key>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.yecc</string>
		</dict>
		<key>nonterminals-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Nonterminals)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.nonterminals.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.nonterminals.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#token</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>rootsymbol-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Rootsymbol)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.rootsymbol.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.rootsymbol.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#token</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-z'])</string>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.rule.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[a-z'])</string>
					<key>end</key>
					<string>\s*(?=-&gt;)</string>
					<key>name</key>
					<string>entity.name.rule.definition.yecc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#token</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(-&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.rule.name-definition.yecc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=:)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#token</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.rule.head-body.yecc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\.)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#rule-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s]</string>
					<key>name</key>
					<string>invalid.illegal.rule-part.yecc</string>
				</dict>
			</array>
		</dict>
		<key>rule-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.expressions.erlang</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.erlang.expression</string>
				</dict>
			</array>
		</dict>
		<key>terminals-directive</key>
		<dict>
			<key>begin</key>
			<string>^\s*(Terminals)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.directive.terminals.yecc</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.directive.end.yecc</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.directive.terminals.yecc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#token</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>token</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>('\$empty')</string>
					<key>name</key>
					<string>keyword.empty-token.yecc</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.begin.yecc</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.token.end.yecc</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.other.token.quoted.yecc</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.escape.yecc</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.escape.yecc</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\\)([bdefnrstv\\'"]|(\^)[@-_]|[0-7]{1,3})</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\\^?.?</string>
							<key>name</key>
							<string>invalid.illegal.token.yecc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[[:lower:]][[:alnum:]@_]*</string>
					<key>name</key>
					<string>entity.name.token.unquoted.yecc</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.yecc</string>
</dict>
</plist>
